# PPMI Data Configuration

# Data paths - Updated for user's actual data structure
data:
  raw_dicom_path: "."  # Root directory containing PPMI_Data 1 and PPMI_Data 2
  clinical_data_path: "."  # Root directory containing CSV files
  processed_path: "data/processed"
  metadata_path: "data/metadata"
  
# Clinical data file names (updated for user's actual files)
clinical_files:
  patient_status: "idaSearch_9_03_2025.csv"
  imaging_metadata: "DaTscan_Imaging_03Sep2025.csv"
  
# Image preprocessing parameters
preprocessing:
  # Target dimensions for registered images
  target_shape: [128, 128, 128]
  
  # Intensity normalization
  normalization_method: "zscore"  # Options: "zscore", "minmax", "percentile"
  
  # Registration parameters
  registration:
    template_path: "templates/mni152.nii.gz"  # MNI152 template path
    interpolation: "Linear"
    optimizer: "GradientDescent"
    metric: "MeanSquares"
    
  # ROI extraction
  roi:
    extract_striatum: true
    striatum_margin: 10  # pixels around striatum
    
# Data splitting
splitting:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_seed: 42
  split_by_patient: true  # Critical: split by patient, not by image
  
# Feature engineering (SBR calculation)
sbr:
  reference_regions: ["occipital_cortex", "cerebellum"]
  striatal_regions: ["left_caudate", "right_caudate", "left_putamen", "right_putamen"]
  
# Model parameters
models:
  classical:
    classifier: "xgboost"  # Options: "logistic", "svm", "xgboost", "lightgbm"
    cv_folds: 5
    
  cnn:
    input_shape: [128, 128, 1]  # Height, width, channels
    batch_size: 16
    epochs: 100
    learning_rate: 0.001
    dropout_rate: 0.5
    
# Evaluation
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1", "auc"]
  cv_folds: 5
  bootstrap_samples: 1000
  
# Output paths
output:
  models: "results/models"
  plots: "results/plots"
  reports: "results/reports"
  predictions: "results/predictions"
